import os
import re
import sys

sys.stdout.reconfigure(encoding='utf-8', errors='replace')

SRC_DIR = 'src'

# Check all Java files and resource files in src
SUSPICIOUS_TERMS = [
    'kimiko', 'catlavan', 'neverlose', 'celestial', 'expensive', 'fluger', 'akrien',
    'nursultan', 'zeroday', 'liquidbounce', 'wurst', 'meteor', 'future', 'rusherhack',
    'baritone', 'impact', 'novoline', 'astolfo', 'rise', 'tenacity', 'vape',
    'zamorozka', 'wild', 'rich', 'deadcode', 'exhibition', 'sigma', 'chatgpt',
    'openai', 'claude', 'gemini', 'deepseek', 'antigravity', 'нейросеть', 'нейросети',
    'llm', 'copilot', 'gpt', 'prompts', 'prompt', 'ai generated', 'generated by'
]

def scan_sources():
    findings = []
    for root, dirs, files in os.walk(SRC_DIR):
        for f in files:
            path = os.path.join(root, f)
            ext = os.path.splitext(f)[1].lower()
            if ext in ('.png', '.jpg', '.ogg', '.ttf', '.jar', '.class', '.exe'):
                continue
            try:
                with open(path, 'r', encoding='utf-8', errors='ignore') as fp:
                    content = fp.read()
                    lines = content.splitlines()
                    for lno, line in enumerate(lines, 1):
                        lower_line = line.lower()
                        for term in SUSPICIOUS_TERMS:
                            # Use word boundary or exact substring
                            if term in lower_line:
                                findings.append((term, path, lno, line.strip()))
            except Exception as e:
                print(f"Error reading {path}: {e}")

    print(f"Total findings in src/: {len(findings)}")
    grouped = {}
    for term, path, lno, line in findings:
        grouped.setdefault(term, []).append((path, lno, line))

    for term, items in grouped.items():
        print(f"\n--- Term: '{term}' ({len(items)} hits) ---")
        for path, lno, line in items:
            print(f"  {path}:{lno}: {line}")

if __name__ == '__main__':
    scan_sources()
